Use travis-after-all script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,7 +20,6 @@ env:
 before_install:
   - sudo apt-get -qq update
   - sudo apt-get -qq install gfortran libblas-dev liblapack-dev >/dev/null
-  - sudo apt-get -qq install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev >/dev/null
   - sudo bash CI/install.sh # Only install texlive and extensions if we need them
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start" #some tests require a display
@@ -41,15 +40,21 @@ script:
   - cd ..
 
 after_script:
-    cd test/output
-    cat test.out
-    cd ../..
+    - |
+        declare exitCode
+        
+        curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
+        exitCode=$?
+
+        if [ $exitCode -eq 0 ]; then
+            python CI/deploy
+        fi
+
+        if [ $exitCode -eq 1 ]; then
+            echo "Build failed - not deploying!!!!!!"
+        fi
 
 deploy:
-  - provider: script
-    script: CI/deploy
-    on:
-        branch: develop
   - provider: pypi
     user: enielse
     password:
